//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheChessBoard.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public uint WatchChessTime {
            get {
                return ((uint)(this["WatchChessTime"]));
            }
            set {
                this["WatchChessTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\ChessArtificialRetard\\bin\\Debug\\ChessArtificialRetard.exe")]
        public string WhiteDefaultExecPath {
            get {
                return ((string)(this["WhiteDefaultExecPath"]));
            }
            set {
                this["WhiteDefaultExecPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WhiteDefaultExecArguments {
            get {
                return ((string)(this["WhiteDefaultExecArguments"]));
            }
            set {
                this["WhiteDefaultExecArguments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\ChessArtificialRetard\\bin\\Debug\\ChessArtificialRetard.exe")]
        public string BlackDefaultExecPath {
            get {
                return ((string)(this["BlackDefaultExecPath"]));
            }
            set {
                this["BlackDefaultExecPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BlackDefaultExecArguments {
            get {
                return ((string)(this["BlackDefaultExecArguments"]));
            }
            set {
                this["BlackDefaultExecArguments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoSaveAIConfig {
            get {
                return ((bool)(this["AutoSaveAIConfig"]));
            }
            set {
                this["AutoSaveAIConfig"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HideAIWindow {
            get {
                return ((bool)(this["HideAIWindow"]));
            }
            set {
                this["HideAIWindow"] = value;
            }
        }
    }
}
